// This file is part of Astarte.
//
// Copyright 2025 SECO Mind Srl
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

use std::io::Write;

use serde::{Deserialize, Serialize};

use crate::error::ErrorKind;
use crate::v101::{ClientMessage, Message, Msgtype, NonceTo2ProveDv, NonceTo2SetupDv};
use crate::Error;

/// ```cddl
/// TO2.Done = [
///     NonceTO2ProveDv;; Nonce generated by Owner Onboarding Service
///                    ;; ...and sent to Device ROE in Msg TO2.ProveOVHdr
/// ]
/// ```
pub(crate) struct Done {
    pub(crate) nonce_to2_prove_dv: NonceTo2ProveDv,
}

impl Serialize for Done {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let Self { nonce_to2_prove_dv } = self;

        (nonce_to2_prove_dv,).serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Done {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (nonce_to2_prove_dv,) = Deserialize::deserialize(deserializer)?;

        Ok(Self { nonce_to2_prove_dv })
    }
}

impl Message for Done {
    const MSG_TYPE: Msgtype = 70;

    fn decode(buf: &[u8]) -> Result<Self, Error> {
        ciborium::from_reader(buf).map_err(|err| {
            #[cfg(feature = "tracing")]
            tracing::error!(error = %err, "couldn't decode TO2.Done");

            Error::new(ErrorKind::Decode, "the TO2.Done")
        })
    }

    fn encode<W>(&self, write: &mut W) -> Result<(), Error>
    where
        W: Write,
    {
        ciborium::into_writer(self, write).map_err(|err| {
            #[cfg(feature = "tracing")]
            tracing::error!(error = %err, "couldn't encode TO2.Done");

            Error::new(ErrorKind::Encode, "the TO2.Done")
        })
    }
}

impl ClientMessage for Done {
    type Response<'a> = Done2;
}

/// ```cddl
/// TO2.Done = [
///     NonceTO2ProveDv;; Nonce generated by Owner Onboarding Service
///                    ;; ...and sent to Device ROE in Msg TO2.ProveOVHdr
/// ]
/// ```
pub(crate) struct Done2 {
    pub(crate) nonce_to2_setup_dv: NonceTo2SetupDv,
}

impl Serialize for Done2 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let Self { nonce_to2_setup_dv } = self;

        (nonce_to2_setup_dv,).serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Done2 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let (nonce_to2_setup_dv,) = Deserialize::deserialize(deserializer)?;

        Ok(Self { nonce_to2_setup_dv })
    }
}

impl Message for Done2 {
    const MSG_TYPE: Msgtype = 71;

    fn decode(buf: &[u8]) -> Result<Self, Error> {
        ciborium::from_reader(buf).map_err(|err| {
            #[cfg(feature = "tracing")]
            tracing::error!(error = %err, "couldn't decode TO2.Done2");

            Error::new(ErrorKind::Decode, "the TO2.Done")
        })
    }

    fn encode<W>(&self, write: &mut W) -> Result<(), Error>
    where
        W: Write,
    {
        ciborium::into_writer(self, write).map_err(|err| {
            #[cfg(feature = "tracing")]
            tracing::error!(error = %err, "couldn't encode TO2.Done2");

            Error::new(ErrorKind::Encode, "the TO2.Done")
        })
    }
}
