# This file is part of Astarte.
#
# Copyright 2025, 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Fedora
FROM fedora:43@sha256:b8f499bee9c97c7c1be0ff7b8b6e4ab72af4216c30d2365c9d474ce2d5c5fd9a

WORKDIR /srv

RUN dnf --assumeyes install libtool awk automake autoconf autoconf-archive && \
    dnf --assumeyes group install development-tools c-development &&\
    dnf --assumeyes builddep tpm2-tss && \
    dnf --assumeyes install libuuid-devel

RUN git clone https://github.com/tpm2-software/tpm2-tss.git

ENTRYPOINT cd /srv/tpm2-tss && \
    ./bootstrap && ./configure --prefix="$PREFIX" && \
    make -j$(nproc) DESTDIR=/out CFLAGS="-Wno-error" && \
    make install
